Repository uracreative/identihub, pull requests merged in 2018-03, with the labels that each got.

#93 Update composer.json
  composer.json
Labels: 1. Backend, bug, in progress

#94 Replaced lorem ipsum
  resources/views/installation/introduction.blade.php
Labels: 1. Backend, 1. Frontend, bug, enhancement, in progress

#95 Fix issue 47
  resources/views/installation/finish.blade.php
Labels: 1. Frontend, enhancement, in progress

#97 Update finish.blade.php
  resources/views/installation/finish.blade.php
Labels: enhancement, in progress

#98 Add react-burger-menu
  package-lock.json
Labels: bug, enhancement, in progress

#99 Update .travis.yml
  .travis.yml
Labels: in progress

#100 Add snapsvg cjs to dependencies
  package-lock.json
  package.json
Labels: bug, enhancement

#101 Update composer and npm lock files
  composer.lock
  package-lock.json
  package.json
Labels: enhancement, in progress

#104 Updated FrontController.php
  app/Http/Controllers/FrontController.php
Labels: 1. Backend, bug, enhancement, feature request, in progress

#108 Fixed spacing issue on organization name .env
  app/Http/Controllers/Installation/InstallationController.php
Labels: 1. Backend, bug, good first issue, in progress

#109 Added viewBox and Scale png
  app/Http/Controllers/Api/V1/SourceFileController.php
Labels: 1. Backend

#111 Added backend support for importing Inkscape Color Swatches
  .travis.yml
  app/Http/Controllers/Api/V1/ColorsController.php
  app/Http/Requests/CreateBulkColorRequest.php
  app/Jobs/CreateBulkColors.php
  app/Models/Color.php
  composer.json
  composer.lock
  database/factories/ModelFactory.php
  database/migrations/2017_08_18_085745_add_slug_column_on_bridges.php
  phpunit.xml
  routes/api.php
  tests/Feature/ColorSwatchAddingTest.php
  tests/Feature/ExampleTest.php
  tests/TestCase.php
  tests/Unit/ColorCanParseSwatch.php
  tests/Unit/ExampleTest.php
  tests/utilities/functions.php
  tests/utilities/open-color.gpl
Labels: 1. Backend

#112 The Svg is now concealed
  .travis.yml
  app/Http/Controllers/Api/V1/SourceFileController.php
  app/Models/Icon.php
  composer.json
  composer.lock
  database/migrations/2018_03_23_123218_add_filename_png_column_on_icons.php
  public/mix-manifest.json
  resources/assets/js/components/BridgeCard.js
  resources/assets/js/components/IconCard.js
  resources/assets/js/pages/Viewer.js
Labels: 1. Backend, in progress

#117 Revert "The Svg is now concealed"
  .travis.yml
  app/Http/Controllers/Api/V1/SourceFileController.php
  app/Models/Icon.php
  composer.json
  composer.lock
  database/migrations/2018_03_23_123218_add_filename_png_column_on_icons.php
  public/mix-manifest.json
  resources/assets/js/components/BridgeCard.js
  resources/assets/js/components/IconCard.js
  resources/assets/js/pages/Viewer.js
Labels: in progress

#118 Revert "Revert "The Svg is now concealed""
  .travis.yml
  app/Http/Controllers/Api/V1/SourceFileController.php
  app/Models/Icon.php
  composer.json
  composer.lock
  database/migrations/2018_03_23_123218_add_filename_png_column_on_icons.php
  public/mix-manifest.json
  resources/assets/js/components/BridgeCard.js
  resources/assets/js/components/IconCard.js
  resources/assets/js/pages/Viewer.js
Labels: in progress

#121 Issue 110 dont display svgs
  app/Models/Icon.php
Labels: in progress

#123 Update ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: enhancement, in progress, needs discussion

#128 Update README.md (Patreon, Screenshots, Logo etc.)
  README.md
Labels: enhancement, in progress
